on:
  push:
    branches:
      - master

permissions:
  actions: read
  checks: write
  contents: read
  id-token: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: node 24
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: docgen
        run: npm run docgen

      - name: build
        run: npm run docs-build

      - name: upload
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs

      - name: deploy
        uses: actions/deploy-pages@v5
        with:
          token: ${{ github.token }}
